// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
struct Sphere
{
    float4 Color;
};

RWStructuredBuffer<sphere> sphereBuffer;
[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;
  
    
    Sphere sphere = sphereBuffer[id.x];
    spheredBuffer[id.x] = sphere;
   
    sphereBuffer[index].Color = float4(1, 0, 0, 1.0);
}
